services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8501:8501"
    networks:
      - dokploy-network
      - default
    volumes:
      - ./.streamlit/secrets.toml:/app/.streamlit/secrets.toml:ro
    environment:
      - PYTHONUNBUFFERED=1

networks:
  dokploy-network:
    external: true

